### ISSUE TITLE
Element com.austingreco.imagelistpreference.ImageListPreference is not allowed here 

### ISSUE THREAD

**Issue by WouterVandenputte** [austingreco/ImageListPreference#4]
First of all, love it that you made this and made it public for everyone

Now for the issue: when adding the following code in `root_preferences.xml`

        <com.austingreco.imagelistpreference.ImageListPreference
            app:key="@string/prefkey_something"
            android:title="@string/some_text"
            android:entries="@array/some_array"
            android:entryValues="@array/some_array"
            app:ilp_entryImages="@array/some_array_images"
            />

Android Studio raises a 'hint': `Element com.austingreco.imagelistpreference.ImageListPreference is not allowed here` but does not say why. Compilation works, but when navigating to the settings screen where this layout is inflated, the app crashes with the following stack trace

> android.view.InflateException: Binary XML file line #33: Error inflating class com.austingreco.imagelistpreference.ImageListPreference
        at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:249)
        at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:277)
        at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:344)
        at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:346)
        at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:157)
        at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:109)
        at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:216)
        at androidx.preference.PreferenceFragmentCompat.setPreferencesFromResource(PreferenceFragmentCompat.java:377)
        at com.mycompany.myapp.SettingsActivity$SettingsFragment.onCreatePreferences(SettingsActivity.kt:40)
        at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1255)
        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1138)
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:136)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1989)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2629)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8024)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassCastException: com.austingreco.imagelistpreference.ImageListPreference cannot be cast to androidx.preference.Preference
        at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:242)
        at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:277) 
        at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:344) 
        at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:346) 
        at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:157) 
        at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:109) 
        at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:216) 
        at androidx.preference.PreferenceFragmentCompat.setPreferencesFromResource(PreferenceFragmentCompat.java:377) 
        at com.mycompany.myapp.SettingsActivity$SettingsFragment.onCreatePreferences(SettingsActivity.kt:40) 
        at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160) 
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684) 
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175) 
        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1255) 
        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1138) 
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:136) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1989) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849) 
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2629) 
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577) 
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247) 
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541) 
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435) 
        at android.app.Activity.performStart(Activity.java:8024) 
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475) 
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221) 
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
I/Process: Sending signal. PID: 25500 SIG: 9

Additionally, this is line 40 of `SettingsActivity`

    class SettingsFragment : PreferenceFragmentCompat() {

       override fun onCreatePreferences(savedInstanceState: Bundle?, rootKey: String?) {
            setPreferencesFromResource(R.xml.root_preferences, rootKey) // line 40
        }
      ..
    }

**Comment by WouterVandenputte** [comment]
The issue is most likely because the library does not use the new `androidx` widgets etc
